---
id: CssMinify
name: CssMinify
full: CSS minification library
description: A library that wraps various CSS minification backends.
list: dev
type: library
authors:
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: lead
version:
  release: 2.0.0alpha3
  api: 2.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/css_parser: ^2
      horde/exception: ^3
      horde/log: ^3
      horde/url: ^3
